name: Setup GitHub Secrets for Stage 2 Deployment

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Google Cloud Project ID'
        required: true
        default: 'api-outreach-as-a-service'
      redis_url:
        description: 'Redis URL'
        required: true
        default: 'redis://localhost:6379'
      jwt_secret:
        description: 'JWT Secret Key'
        required: true
        type: string
      growchief_endpoint:
        description: 'GrowChief API Endpoint'
        required: true
        default: 'https://api.growchief.com'
      growchief_api_key:
        description: 'GrowChief API Key'
        required: true
        type: string
      google_client_id:
        description: 'Google OAuth Client ID'
        required: true
        type: string
      google_client_secret:
        description: 'Google OAuth Client Secret'
        required: true
        type: string
      slack_webhook_url:
        description: 'Slack Webhook URL (optional)'
        required: false
        type: string

jobs:
  setup-secrets:
    name: Setup GitHub Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Get project number
      id: project
      run: |
        PROJECT_NUMBER=$(gcloud projects describe ${{ github.event.inputs.project_id }} --format="value(projectNumber)")
        echo "project-number=$PROJECT_NUMBER" >> $GITHUB_OUTPUT
        echo "Project Number: $PROJECT_NUMBER"
    
    - name: Get Workload Identity Provider
      id: wif
      run: |
        WIF_PROVIDER="projects/${{ steps.project.outputs.project-number }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
        echo "wif-provider=$WIF_PROVIDER" >> $GITHUB_OUTPUT
        echo "WIF Provider: $WIF_PROVIDER"
    
    - name: Set GitHub Secrets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set WIF Provider
        echo "${{ steps.wif.outputs.wif-provider }}" | gh secret set WIF_PROVIDER
        
        # Set Service Account
        echo "github-actions@${{ github.event.inputs.project_id }}.iam.gserviceaccount.com" | gh secret set WIF_SERVICE_ACCOUNT
        
        # Set Application Secrets
        echo "${{ github.event.inputs.redis_url }}" | gh secret set REDIS_URL
        echo "${{ github.event.inputs.jwt_secret }}" | gh secret set JWT_SECRET
        echo "${{ github.event.inputs.growchief_endpoint }}" | gh secret set GROWCHIEF_ENDPOINT
        echo "${{ github.event.inputs.growchief_api_key }}" | gh secret set GROWCHIEF_API_KEY
        echo "${{ github.event.inputs.google_client_id }}" | gh secret set GOOGLE_CLIENT_ID
        echo "${{ github.event.inputs.google_client_secret }}" | gh secret set GOOGLE_CLIENT_SECRET
        
        # Set optional Slack webhook
        if [[ -n "${{ github.event.inputs.slack_webhook_url }}" ]]; then
          echo "${{ github.event.inputs.slack_webhook_url }}" | gh secret set SLACK_WEBHOOK_URL
        fi
        
        echo "✅ All secrets have been set successfully!"
    
    - name: Verify secrets
      run: |
        echo "🔍 Verifying secrets..."
        gh secret list
        
        echo ""
        echo "📋 Secrets Summary:"
        echo "  WIF_PROVIDER: Set"
        echo "  WIF_SERVICE_ACCOUNT: Set"
        echo "  REDIS_URL: Set"
        echo "  JWT_SECRET: Set"
        echo "  GROWCHIEF_ENDPOINT: Set"
        echo "  GROWCHIEF_API_KEY: Set"
        echo "  GOOGLE_CLIENT_ID: Set"
        echo "  GOOGLE_CLIENT_SECRET: Set"
        if [[ -n "${{ github.event.inputs.slack_webhook_url }}" ]]; then
          echo "  SLACK_WEBHOOK_URL: Set"
        fi
        echo ""
        echo "🎉 Setup complete! You can now run the Stage 2 deployment pipeline."
